### PR TITLE
Use of DefaultSignatures, version bump, etc.

### PR DESCRIPTION
**Pull request by andysonnenburg**
Many defaults were added where DefaultSignatures is available (with no changes otherwise).  The module was renamed to match the mtl style, and a new module was added (also to follow the mtl style).  The version was bumped, as well as a dependency version.  Additional minor changes were also made.

### CODE REVIEW

**Comment by mainland** [comment]
Hi Andy,

It looks like you renamed a file, modified some code to use your preferred style, changed some code to use DefaultSignatures, and changed the .cabal file to reference your git repository instead of mine. Are there any functional changes?

**Comment by andysonnenburg** [comment]
That's pretty much it - the only really major parts are DefaultSignatures, the module rename, and the looser restrictions on stm.  I should have probably created a separate branch for the pull request to eliminate the git repository change and formatting, and can create one later today.

**Comment by mainland** [comment]
mtl doesn't use DefaultSignatures, so I'm disinclined to use it. What is the concrete advantage of using it in this package?

**Comment by andysonnenburg** [comment]
There is no real advantage (beyond a few lines of code per instance).  I do wish mtl used it, but I can see why not (no fun checking if its available every time you want to write a portable instance declaration).

That being said, it is an extremely convenient extension.  It is only required at the place of default method definition, and if one is already using other extensions that require a newer version of GHC (DataKinds, etc.), there is no point in writing the trivial methods that just forward down the stack (assuming one is also avoiding GeneralizedNewtypeDeriving - it is not available in Safe Haskell).  The way the extension is used in my branch should keep everything portable, too.

**Pull request closed without merging**
